/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_miniproject;
import java.sql.*;  
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pratyush
 */
public class Mainform extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Mainform() {
        initComponents();
    }
    
    viewresult vr = new viewresult();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FY = new javax.swing.JRadioButton();
        SY = new javax.swing.JRadioButton();
        TY = new javax.swing.JRadioButton();
        LY = new javax.swing.JRadioButton();
        name = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ema = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameo = new javax.swing.JLabel();
        rollnoo = new javax.swing.JLabel();
        yoso = new javax.swing.JLabel();
        emao = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ise1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ia1 = new javax.swing.JTextField();
        ese1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ise2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ia2 = new javax.swing.JTextField();
        ese2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ise3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ia3 = new javax.swing.JTextField();
        ese3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ise4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        ia4 = new javax.swing.JTextField();
        ese4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        ise5 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        ia5 = new javax.swing.JTextField();
        ese5 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(565, 650));
        setMinimumSize(new java.awt.Dimension(565, 650));
        setPreferredSize(new java.awt.Dimension(565, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 56, 31));

        jLabel2.setText("Roll No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 50, 22));

        jLabel3.setText("Year Of Study");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 103, -1));

        FY.setText("FY");
        FY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FYActionPerformed(evt);
            }
        });
        getContentPane().add(FY, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        SY.setText("SY");
        SY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SYActionPerformed(evt);
            }
        });
        getContentPane().add(SY, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        TY.setText("TY");
        TY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYActionPerformed(evt);
            }
        });
        getContentPane().add(TY, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        LY.setText("LY");
        LY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LYActionPerformed(evt);
            }
        });
        getContentPane().add(LY, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 400, -1));

        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        getContentPane().add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 400, -1));

        jLabel4.setText("E-mail ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        ema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaActionPerformed(evt);
            }
        });
        getContentPane().add(ema, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 187, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));
        getContentPane().add(nameo, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 237, 737, -1));
        getContentPane().add(rollnoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 243, 250, -1));
        getContentPane().add(yoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 278, 250, -1));
        getContentPane().add(emao, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 284, 250, -1));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setText("Display");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 82, -1));

        ise1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise1ActionPerformed(evt);
            }
        });
        getContentPane().add(ise1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 60, -1));

        jLabel5.setText("ESE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 30, 20));
        getContentPane().add(ia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 60, -1));

        ese1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese1ActionPerformed(evt);
            }
        });
        getContentPane().add(ese1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 60, -1));

        jLabel8.setText("out of 50");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 78, -1));

        jLabel9.setText("out of 20");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 78, -1));

        jLabel11.setText("DAM");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 30, 20));

        jLabel12.setText("ISE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 30, 20));

        jLabel13.setText("out of 30");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 78, -1));

        jLabel14.setText("IA");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 30, 20));

        ise2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise2ActionPerformed(evt);
            }
        });
        getContentPane().add(ise2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 60, -1));

        jLabel6.setText("ESE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 30, 20));
        getContentPane().add(ia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 60, -1));

        ese2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese2ActionPerformed(evt);
            }
        });
        getContentPane().add(ese2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 60, -1));

        jLabel10.setText("out of 50");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 78, -1));

        jLabel15.setText("out of 20");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 78, -1));

        jLabel16.setText("DS");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 30, 20));

        jLabel17.setText("ISE");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 30, 20));

        jLabel18.setText("out of 30");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 78, -1));

        jLabel19.setText("IA");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 30, 20));

        ise3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise3ActionPerformed(evt);
            }
        });
        getContentPane().add(ise3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 60, -1));

        jLabel7.setText("ESE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 30, 20));
        getContentPane().add(ia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 60, -1));

        ese3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese3ActionPerformed(evt);
            }
        });
        getContentPane().add(ese3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 60, -1));

        jLabel20.setText("out of 50");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 78, -1));

        jLabel21.setText("out of 20");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 78, -1));

        jLabel22.setText("DMS");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 30, 20));

        jLabel23.setText("ISE");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 30, 20));

        jLabel24.setText("out of 30");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 78, -1));

        jLabel25.setText("IA");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 30, 20));

        ise4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise4ActionPerformed(evt);
            }
        });
        getContentPane().add(ise4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 60, -1));

        jLabel26.setText("ESE");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 30, 20));
        getContentPane().add(ia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 60, -1));

        ese4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese4ActionPerformed(evt);
            }
        });
        getContentPane().add(ese4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 60, -1));

        jLabel27.setText("out of 50");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 78, -1));

        jLabel28.setText("out of 20");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 78, -1));

        jLabel29.setText("DIS");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 30, 20));

        jLabel30.setText("ISE");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 30, 20));

        jLabel31.setText("out of 30");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 78, -1));

        jLabel32.setText("IA");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 30, 20));

        ise5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise5ActionPerformed(evt);
            }
        });
        getContentPane().add(ise5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 60, -1));

        jLabel33.setText("ESE");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 30, 20));
        getContentPane().add(ia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 60, -1));

        ese5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese5ActionPerformed(evt);
            }
        });
        getContentPane().add(ese5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 60, -1));

        jLabel34.setText("out of 50");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 78, -1));

        jLabel35.setText("out of 20");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 78, -1));

        jLabel36.setText("JAVA");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 30, 20));

        jLabel37.setText("ISE");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 30, 20));

        jLabel38.setText("out of 30");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 78, -1));

        jLabel39.setText("IA");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 30, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FYActionPerformed
        // TODO add your handling code here:
        if(FY.isSelected()){
            SY.setSelected(false);
            TY.setSelected(false);
            LY.setSelected(false);
        }
    }//GEN-LAST:event_FYActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst=null;
        Connection con = null;
        
        long a = Long.parseLong(roll.getText());
        String namee = name.getText();
        String yos = "";
        if(FY.isSelected()){
           
            yos = "FY";
            
        }
        else if(SY.isSelected()){
             yos = "SY";
           
        }
        else if(TY.isSelected()){
             yos = "TY";
            
        }
        else if(LY.isSelected()){
             yos = "LY";
            
        }
        int is1 = Integer.parseInt(ise1.getText());
        int i1 = Integer.parseInt(ia1.getText());
        int es1 = Integer.parseInt(ese1.getText());
        int m1 = is1+i1+es1;
        
        int is2 = Integer.parseInt(ise2.getText());
        int i2 = Integer.parseInt(ia2.getText());
        int es2 = Integer.parseInt(ese2.getText());
        int m2 = is2+i2+es2;
        
        int is3 = Integer.parseInt(ise3.getText());
        int i3 = Integer.parseInt(ia3.getText());
        int es3 = Integer.parseInt(ese3.getText());
        int m3 = is3+i3+es3;
        
        int is4 = Integer.parseInt(ise4.getText());
        int i4 = Integer.parseInt(ia4.getText());
        int es4 = Integer.parseInt(ese4.getText());
        int m4 = is4+i4+es4;
        
        int is5 = Integer.parseInt(ise5.getText());
        int i5 = Integer.parseInt(ia5.getText());
        int es5 = Integer.parseInt(ese5.getText());
        int m5 = is5+i5+es5;
        if(m1 > 100 || m2 > 100 || m3 > 100 || m4 > 100 || m5 > 100){
            JOptionPane.showMessageDialog(this,"Wrong input for marks");
        }
        else{
        int t = m1+m2+m3+m4+m5;
        float p = t/5;
        char g = 'A';
        if(p>=80){
            g ='A';
        }
        else if(p>=70 && p<80){
            g ='B';
        }
        else if(p>=60 && p<70){
            g ='C';
        }
        else if(p>=50 && p<60){
           g ='D';
        }
        else if(p>=40 && p<50){
            g ='E';
        }
        else if(p<40){
            g ='F';
        }
        String gs =String.valueOf(g);  
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/new?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            pst = con.prepareStatement("insert into student values(?,?,?,?,?,?,?)");
            pst.setString(1,name.getText());
            pst.setLong(2,a);
            pst.setString(3,yos);
            pst.setString(4,ema.getText());
            pst.setInt(5,t);
            pst.setFloat(6, p);
            pst.setString(7, gs);
      
            
            
            int r = pst.executeUpdate();
            pst.close();
            con.close();
}
        catch(Exception e){ System.out.println("ERROR"+ e); }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nameActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rollActionPerformed

    private void emaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_emaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        name.setText(null);
        roll.setText(null);
        ema.setText(null);
        FY.setSelected(false);
        SY.setSelected(false);
        TY.setSelected(false);
        LY.setSelected(false);
        ise1.setText(null);
        ese1.setText(null);
        ia1.setText(null);
        ise2.setText(null);
        ese2.setText(null);
        ia2.setText(null);
        ise3.setText(null);
        ese3.setText(null);
        ia3.setText(null);
        ise4.setText(null);
        ese4.setText(null);
        ia4.setText(null);
        ise5.setText(null);
        ese5.setText(null);
        ia5.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SYActionPerformed
        // TODO add your handling code here:
        if(SY.isSelected()){
            FY.setSelected(false);
            TY.setSelected(false);
            LY.setSelected(false);
        }
    }//GEN-LAST:event_SYActionPerformed

    private void TYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYActionPerformed
        // TODO add your handling code here:
        if(TY.isSelected()){
            FY.setSelected(false);
            SY.setSelected(false);
            LY.setSelected(false);
        }
    }//GEN-LAST:event_TYActionPerformed

    private void LYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LYActionPerformed
        // TODO add your handling code here:
        if(LY.isSelected()){
            SY.setSelected(false);
            TY.setSelected(false);
            FY.setSelected(false);
        }
    }//GEN-LAST:event_LYActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      
       try{
        DefaultTableModel tb = (DefaultTableModel)vr.jTable1.getModel(); 
        tb.setRowCount(0);
        Connection con = null;
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/new?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from student");
        
        while(rs.next()){
            String name = rs.getString("name");
            String roll = String.valueOf(rs.getLong("rollno"));
            String yos = rs.getString("yearofstudy");
            String ema = rs.getString("email");
            String tmark = String.valueOf(rs.getInt("TotalMarks"));
            String per = String.valueOf(rs.getFloat("Percentage"));
            String grade = rs.getString("Grade");
            
            String tdata[] = {name,roll,yos,ema,tmark,per,grade};
            
            tb.addRow(tdata);
            
            
        }
        vr.jTable1.setAutoCreateRowSorter(true);
       
         
        con.close();
        } catch(Exception e){ System.out.println("ERROR"+ e); } 
       
       vr.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ise1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise1ActionPerformed

    private void ese1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese1ActionPerformed

    private void ise2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise2ActionPerformed

    private void ese2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese2ActionPerformed

    private void ise3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise3ActionPerformed

    private void ese3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese3ActionPerformed

    private void ise4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise4ActionPerformed

    private void ese4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese4ActionPerformed

    private void ise5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise5ActionPerformed

    private void ese5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese5ActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FY;
    private javax.swing.JRadioButton LY;
    private javax.swing.JRadioButton SY;
    private javax.swing.JRadioButton TY;
    private javax.swing.JTextField ema;
    private javax.swing.JLabel emao;
    private javax.swing.JTextField ese1;
    private javax.swing.JTextField ese2;
    private javax.swing.JTextField ese3;
    private javax.swing.JTextField ese4;
    private javax.swing.JTextField ese5;
    private javax.swing.JTextField ia1;
    private javax.swing.JTextField ia2;
    private javax.swing.JTextField ia3;
    private javax.swing.JTextField ia4;
    private javax.swing.JTextField ia5;
    private javax.swing.JTextField ise1;
    private javax.swing.JTextField ise2;
    private javax.swing.JTextField ise3;
    private javax.swing.JTextField ise4;
    private javax.swing.JTextField ise5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameo;
    private javax.swing.JTextField roll;
    private javax.swing.JLabel rollnoo;
    private javax.swing.JLabel yoso;
    // End of variables declaration//GEN-END:variables
}
