/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_miniproject;
import java.sql.*;  
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pratyush
 */
public class Mainform extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Mainform() {
        initComponents();
    }
    
    viewresult vr = new viewresult();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FY = new javax.swing.JRadioButton();
        SY = new javax.swing.JRadioButton();
        TY = new javax.swing.JRadioButton();
        LY = new javax.swing.JRadioButton();
        name = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ema = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameo = new javax.swing.JLabel();
        rollnoo = new javax.swing.JLabel();
        yoso = new javax.swing.JLabel();
        emao = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        mark1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mark2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mark3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(518, 350));
        setMinimumSize(new java.awt.Dimension(518, 350));
        setPreferredSize(new java.awt.Dimension(518, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 11, 56, 31));

        jLabel2.setText("Roll No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 48, 50, 22));

        jLabel3.setText("Year Of Study");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 88, 103, -1));

        FY.setText("FY");
        FY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FYActionPerformed(evt);
            }
        });
        getContentPane().add(FY, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 107, -1, -1));

        SY.setText("SY");
        SY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SYActionPerformed(evt);
            }
        });
        getContentPane().add(SY, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 107, -1, -1));

        TY.setText("TY");
        TY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYActionPerformed(evt);
            }
        });
        getContentPane().add(TY, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 107, -1, -1));

        LY.setText("LY");
        LY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LYActionPerformed(evt);
            }
        });
        getContentPane().add(LY, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 107, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 16, 400, -1));

        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        getContentPane().add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 400, -1));

        jLabel4.setText("E-mail ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 135, -1, -1));

        ema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaActionPerformed(evt);
            }
        });
        getContentPane().add(ema, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 132, 187, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 278, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 278, -1, -1));
        getContentPane().add(nameo, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 237, 737, -1));
        getContentPane().add(rollnoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 243, 250, -1));
        getContentPane().add(yoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 278, 250, -1));
        getContentPane().add(emao, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 284, 250, -1));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setText("Display");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 278, 82, -1));

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 278, 85, -1));

        jButton5.setBackground(new java.awt.Color(255, 204, 255));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 278, 77, -1));

        mark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark1ActionPerformed(evt);
            }
        });
        getContentPane().add(mark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 170, 60, -1));

        jLabel5.setText("Java Marks");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 173, -1, -1));

        jLabel6.setText("Python Marks");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 204, 79, -1));
        getContentPane().add(mark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 201, 60, -1));

        jLabel7.setText("Cpp Marks");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 240, 63, -1));

        mark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark3ActionPerformed(evt);
            }
        });
        getContentPane().add(mark3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 237, 60, -1));

        jLabel8.setText("out of 100");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 173, 78, -1));

        jLabel9.setText("out of 100");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 240, 78, -1));

        jLabel10.setText("out of 100");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 204, 78, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FYActionPerformed
        // TODO add your handling code here:
        if(FY.isSelected()){
            SY.setSelected(false);
            TY.setSelected(false);
            LY.setSelected(false);
        }
    }//GEN-LAST:event_FYActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst=null;
        Connection con = null;
        
        int a = Integer.parseInt(roll.getText());
        String namee = name.getText();
        String yos = "";
        if(FY.isSelected()){
           
            yos = "FY";
            
        }
        else if(SY.isSelected()){
             yos = "SY";
           
        }
        else if(TY.isSelected()){
             yos = "TY";
            
        }
        else if(LY.isSelected()){
             yos = "LY";
            
        }
        int m1 = Integer.parseInt(mark1.getText());
        int m2 = Integer.parseInt(mark2.getText());
        int m3 = Integer.parseInt(mark3.getText());
        if(m1 > 100 || m2 > 100 || m3 > 100){
            JOptionPane.showMessageDialog(this,"Wrong input for marks");
        }
        else{
        int t = m1+m2+m3;
        float p = t/3;
        char g = 'A';
        if(p>=80){
            g ='A';
        }
        else if(p>=70 && p<80){
            g ='B';
        }
        else if(p>=60 && p<70){
            g ='C';
        }
        else if(p>=50 && p<60){
           g ='D';
        }
        else if(p>=40 && p<50){
            g ='E';
        }
        else if(p<40){
            g ='F';
        }
        String gs =String.valueOf(g);  
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/new?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            pst = con.prepareStatement("insert into student values(?,?,?,?,?,?,?)");
            pst.setString(1,name.getText());
            pst.setInt(2,a);
            pst.setString(3,yos);
            pst.setString(4,ema.getText());
            pst.setInt(5,t);
            pst.setFloat(6, p);
            pst.setString(7, gs);
      
            
            
            int r = pst.executeUpdate();
            pst.close();
            con.close();
}
        catch(Exception e){ System.out.println("ERROR"+ e); }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nameActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rollActionPerformed

    private void emaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_emaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        name.setText(null);
        roll.setText(null);
        ema.setText(null);
        FY.setSelected(false);
        SY.setSelected(false);
        TY.setSelected(false);
        LY.setSelected(false);
        mark1.setText(null);
        mark3.setText(null);
        mark2.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SYActionPerformed
        // TODO add your handling code here:
        if(SY.isSelected()){
            FY.setSelected(false);
            TY.setSelected(false);
            LY.setSelected(false);
        }
    }//GEN-LAST:event_SYActionPerformed

    private void TYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYActionPerformed
        // TODO add your handling code here:
        if(TY.isSelected()){
            FY.setSelected(false);
            SY.setSelected(false);
            LY.setSelected(false);
        }
    }//GEN-LAST:event_TYActionPerformed

    private void LYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LYActionPerformed
        // TODO add your handling code here:
        if(LY.isSelected()){
            SY.setSelected(false);
            TY.setSelected(false);
            FY.setSelected(false);
        }
    }//GEN-LAST:event_LYActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      
       try{
        DefaultTableModel tb = (DefaultTableModel)vr.jTable1.getModel(); 
        tb.setRowCount(0);
        Connection con = null;
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/new?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from student");
        
        while(rs.next()){
            String name = rs.getString("name");
            String roll = String.valueOf(rs.getInt("rollno"));
            String yos = rs.getString("yearofstudy");
            String ema = rs.getString("email");
            String tmark = String.valueOf(rs.getInt("TotalMarks"));
            String per = String.valueOf(rs.getFloat("Percentage"));
            String grade = rs.getString("Grade");
            
            String tdata[] = {name,roll,yos,ema,tmark,per,grade};
            
            tb.addRow(tdata);
        }
       
         
        con.close();
        } catch(Exception e){ System.out.println("ERROR"+ e); } 
       
       vr.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        PreparedStatement pst=null;
        Connection con = null;
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/new?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
        pst = con.prepareStatement("update student set rollno=?, yearofstudy=?, email=? , TotalMarks=? ,Percentage=?,Grade=?  where name=? ");
        int a = Integer.parseInt(roll.getText());
        String yos = "";
        if(FY.isSelected()){
            yos = "FY";
        }
        else if(SY.isSelected()){
             yos = "SY"; 
        }
        else if(TY.isSelected()){
             yos = "TY";
        }
        else if(LY.isSelected()){
             yos = "LY";
        
        }
        int m1 = Integer.parseInt(mark1.getText());
        int m2 = Integer.parseInt(mark2.getText());
        int m3 = Integer.parseInt(mark3.getText());
        int t = m1+m2+m3;
        float p = t/3;
        char g = 'A';
        if(p>=80){
            g ='A';
        }
        else if(p>=70 && p<80){
            g ='B';
        }
        else if(p>=60 && p<70){
            g ='C';
        }
        else if(p>=50 && p<60){
           g ='D';
        }
        else if(p>=40 && p<50){
            g ='E';
        }
        else if(p<40){
            g ='F';
        }
        String gs =String.valueOf(g); 
        pst.setInt(1,a);
        pst.setString(2,yos);
        pst.setString(3,ema.getText());
        pst.setInt(4,t);
        pst.setFloat(5, p);
        pst.setString(6, gs);
        pst.setString(7,name.getText());
        
        int r = pst.executeUpdate();
        pst.close();
        con.close();
        
        
        }  catch(Exception e){ System.out.println("ERROR"+ e); } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
        PreparedStatement pst=null;
        Connection con = null;
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/new?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
        pst = con.prepareStatement("delete from student where name=? and rollno=? and yearofstudy=? and email=? ");
        int a = Integer.parseInt(roll.getText());
        String yos = "";
        if(FY.isSelected()){
            yos = "FY";
        }
        else if(SY.isSelected()){
             yos = "SY"; 
        }
        else if(TY.isSelected()){
             yos = "TY";
        }
        else if(LY.isSelected()){
             yos = "LY";
        
        }
        pst.setString(1,name.getText());
        pst.setInt(2,a);
        pst.setString(3,yos);
        pst.setString(4,ema.getText());
        
        
        int r = pst.executeUpdate();
        pst.close();
        con.close();
        
        
        }catch(Exception e){ System.out.println("ERROR"+ e); } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void mark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark1ActionPerformed

    private void mark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark3ActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FY;
    private javax.swing.JRadioButton LY;
    private javax.swing.JRadioButton SY;
    private javax.swing.JRadioButton TY;
    private javax.swing.JTextField ema;
    private javax.swing.JLabel emao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mark1;
    private javax.swing.JTextField mark2;
    private javax.swing.JTextField mark3;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameo;
    private javax.swing.JTextField roll;
    private javax.swing.JLabel rollnoo;
    private javax.swing.JLabel yoso;
    // End of variables declaration//GEN-END:variables
}
