/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_miniproject;
import java.sql.*;  
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pratyush
 */
public class updateform extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public updateform() {
        initComponents();
    }
    
    viewresult vr = new viewresult();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        nameo = new javax.swing.JLabel();
        rollnoo = new javax.swing.JLabel();
        yoso = new javax.swing.JLabel();
        emao = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ise1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ia1 = new javax.swing.JTextField();
        ese1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ise2 = new javax.swing.JTextField();
        ia2 = new javax.swing.JTextField();
        ese2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ise3 = new javax.swing.JTextField();
        ia3 = new javax.swing.JTextField();
        ese3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ise4 = new javax.swing.JTextField();
        ia4 = new javax.swing.JTextField();
        ese4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ise5 = new javax.swing.JTextField();
        ia5 = new javax.swing.JTextField();
        ese5 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        FY = new javax.swing.JRadioButton();
        SY = new javax.swing.JRadioButton();
        TY = new javax.swing.JRadioButton();
        LY = new javax.swing.JRadioButton();
        ema = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(565, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 720, 100, -1));
        getContentPane().add(nameo, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 237, 737, -1));
        getContentPane().add(rollnoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 243, 250, -1));
        getContentPane().add(yoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 278, 250, -1));
        getContentPane().add(emao, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 284, 250, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton3.setText("Display");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 720, 100, -1));

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 720, -1, -1));

        ise1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ise1.setForeground(new java.awt.Color(0, 204, 204));
        ise1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise1ActionPerformed(evt);
            }
        });
        getContentPane().add(ise1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 80, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("ESE MARKS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 120, 30));

        ia1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ia1.setForeground(new java.awt.Color(0, 204, 204));
        getContentPane().add(ia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 90, 30));

        ese1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ese1.setForeground(new java.awt.Color(0, 204, 204));
        ese1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese1ActionPerformed(evt);
            }
        });
        getContentPane().add(ese1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 100, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("out of 50");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 90, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("out of 20");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 90, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("DAM");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 50, 20));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText(" ISE MARKS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 120, 20));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("out of 30");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 90, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("IA MARKS");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 110, 30));

        ise2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ise2.setForeground(new java.awt.Color(0, 204, 204));
        ise2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise2ActionPerformed(evt);
            }
        });
        getContentPane().add(ise2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 80, 30));

        ia2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ia2.setForeground(new java.awt.Color(0, 204, 204));
        getContentPane().add(ia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 90, 30));

        ese2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ese2.setForeground(new java.awt.Color(0, 204, 204));
        ese2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese2ActionPerformed(evt);
            }
        });
        getContentPane().add(ese2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 100, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("out of 50");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 90, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 204));
        jLabel15.setText("out of 20");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 90, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("DS");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 50, 20));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 204));
        jLabel18.setText("out of 30");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 90, -1));

        ise3.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ise3.setForeground(new java.awt.Color(0, 204, 204));
        ise3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise3ActionPerformed(evt);
            }
        });
        getContentPane().add(ise3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 80, 30));

        ia3.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ia3.setForeground(new java.awt.Color(0, 204, 204));
        getContentPane().add(ia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 90, 30));

        ese3.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ese3.setForeground(new java.awt.Color(0, 204, 204));
        ese3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese3ActionPerformed(evt);
            }
        });
        getContentPane().add(ese3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 100, 30));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 204));
        jLabel20.setText("out of 50");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 90, 30));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 204));
        jLabel21.setText("out of 20");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 90, -1));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 204));
        jLabel22.setText("DMS");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 50, 20));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 204, 204));
        jLabel24.setText("out of 30");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 90, -1));

        ise4.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ise4.setForeground(new java.awt.Color(0, 204, 204));
        ise4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise4ActionPerformed(evt);
            }
        });
        getContentPane().add(ise4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 80, 30));

        ia4.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ia4.setForeground(new java.awt.Color(0, 204, 204));
        getContentPane().add(ia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 90, 30));

        ese4.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ese4.setForeground(new java.awt.Color(0, 204, 204));
        ese4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese4ActionPerformed(evt);
            }
        });
        getContentPane().add(ese4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, 100, 30));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 204, 204));
        jLabel27.setText("out of 50");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 90, -1));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 204, 204));
        jLabel28.setText("out of 20");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 90, -1));

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 204, 204));
        jLabel29.setText("DIS");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 50, 20));

        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 204, 204));
        jLabel31.setText("out of 30");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 90, -1));

        ise5.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ise5.setForeground(new java.awt.Color(0, 204, 204));
        ise5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ise5ActionPerformed(evt);
            }
        });
        getContentPane().add(ise5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 80, 30));

        ia5.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ia5.setForeground(new java.awt.Color(0, 204, 204));
        ia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ia5ActionPerformed(evt);
            }
        });
        getContentPane().add(ia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 90, 30));

        ese5.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ese5.setForeground(new java.awt.Color(0, 204, 204));
        ese5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ese5ActionPerformed(evt);
            }
        });
        getContentPane().add(ese5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, 100, 30));

        jLabel34.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 204, 204));
        jLabel34.setText("out of 50");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 90, -1));

        jLabel35.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 204, 204));
        jLabel35.setText("out of 20");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 90, -1));

        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 204, 204));
        jLabel36.setText("JAVA");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 50, 20));

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 204, 204));
        jLabel38.setText("out of 30");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, 90, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Year Of Study:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 130, -1));

        FY.setBackground(new java.awt.Color(0, 0, 0));
        FY.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        FY.setForeground(new java.awt.Color(0, 204, 204));
        FY.setText("FY");
        FY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FYActionPerformed(evt);
            }
        });
        jPanel1.add(FY, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        SY.setBackground(new java.awt.Color(0, 0, 0));
        SY.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        SY.setForeground(new java.awt.Color(0, 204, 204));
        SY.setText("SY");
        SY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SYActionPerformed(evt);
            }
        });
        jPanel1.add(SY, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        TY.setBackground(new java.awt.Color(0, 0, 0));
        TY.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        TY.setForeground(new java.awt.Color(0, 204, 204));
        TY.setText("TY");
        TY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYActionPerformed(evt);
            }
        });
        jPanel1.add(TY, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        LY.setBackground(new java.awt.Color(0, 0, 0));
        LY.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        LY.setForeground(new java.awt.Color(0, 204, 204));
        LY.setText("LY");
        LY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LYActionPerformed(evt);
            }
        });
        jPanel1.add(LY, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, -1));

        ema.setForeground(new java.awt.Color(0, 204, 204));
        ema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaActionPerformed(evt);
            }
        });
        jPanel1.add(ema, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 190, 30));

        roll.setForeground(new java.awt.Color(0, 204, 204));
        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        jPanel1.add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 190, 30));

        name.setForeground(new java.awt.Color(0, 204, 204));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 190, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("E-mail :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 90, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Roll No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 90, 22));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 80, 31));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel6.setText("Student Details:");
        jPanel2.add(jLabel6);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 610, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 790, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FYActionPerformed
        // TODO add your handling code here:
        if(FY.isSelected()){
            SY.setSelected(false);
            TY.setSelected(false);
            LY.setSelected(false);
        }
    }//GEN-LAST:event_FYActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nameActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rollActionPerformed

    private void emaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_emaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        name.setText(null);
        roll.setText(null);
        ema.setText(null);
        FY.setSelected(false);
        SY.setSelected(false);
        TY.setSelected(false);
        LY.setSelected(false);
        ise1.setText(null);
        ese1.setText(null);
        ia1.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SYActionPerformed
        // TODO add your handling code here:
        if(SY.isSelected()){
            FY.setSelected(false);
            TY.setSelected(false);
            LY.setSelected(false);
        }
    }//GEN-LAST:event_SYActionPerformed

    private void TYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYActionPerformed
        // TODO add your handling code here:
        if(TY.isSelected()){
            FY.setSelected(false);
            SY.setSelected(false);
            LY.setSelected(false);
        }
    }//GEN-LAST:event_TYActionPerformed

    private void LYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LYActionPerformed
        // TODO add your handling code here:
        if(LY.isSelected()){
            SY.setSelected(false);
            TY.setSelected(false);
            FY.setSelected(false);
        }
    }//GEN-LAST:event_LYActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      
       try{
        DefaultTableModel tb = (DefaultTableModel)vr.jTable1.getModel(); 
        tb.setRowCount(0);
        Connection con = null;
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/new?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from student");
        
        while(rs.next()){
            String name = rs.getString("name");
            String roll = String.valueOf(rs.getLong("rollno"));
            String yos = rs.getString("yearofstudy");
            String ema = rs.getString("email");
            String tmark = String.valueOf(rs.getInt("TotalMarks"));
            String per = String.valueOf(rs.getFloat("Percentage"));
            String grade = rs.getString("Grade");
            
            String tdata[] = {name,roll,yos,ema,tmark,per,grade};
            
            tb.addRow(tdata);
            
            
        }
        vr.jTable1.setAutoCreateRowSorter(true);
       
         
        con.close();
        } catch(Exception e){ System.out.println("ERROR"+ e); } 
       
       vr.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        PreparedStatement pst=null;
        Connection con = null;
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/new?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
        pst = con.prepareStatement("update student set rollno=?, yearofstudy=?, email=? , TotalMarks=? ,Percentage=?,Grade=?  where name=? ");
        long a = Long.parseLong(roll.getText());
        String yos = "";
        if(FY.isSelected()){
            yos = "FY";
        }
        else if(SY.isSelected()){
             yos = "SY"; 
        }
        else if(TY.isSelected()){
             yos = "TY";
        }
        else if(LY.isSelected()){
             yos = "LY";
        
        }
        int is1 = Integer.parseInt(ise1.getText());
        int i1 = Integer.parseInt(ia1.getText());
        int es1 = Integer.parseInt(ese1.getText());
        int m1 = is1+i1+es1;
        
        int is2 = Integer.parseInt(ise2.getText());
        int i2 = Integer.parseInt(ia2.getText());
        int es2 = Integer.parseInt(ese2.getText());
        int m2 = is2+i2+es2;
        
        int is3 = Integer.parseInt(ise3.getText());
        int i3 = Integer.parseInt(ia3.getText());
        int es3 = Integer.parseInt(ese3.getText());
        int m3 = is3+i3+es3;
        
        int is4 = Integer.parseInt(ise4.getText());
        int i4 = Integer.parseInt(ia4.getText());
        int es4 = Integer.parseInt(ese4.getText());
        int m4 = is4+i4+es4;
        
        int is5 = Integer.parseInt(ise5.getText());
        int i5 = Integer.parseInt(ia5.getText());
        int es5 = Integer.parseInt(ese5.getText());
        int m5 = is5+i5+es5;
        if(m1 > 100 || m2 > 100 || m3 > 100 || m4 > 100 || m5 > 100){
            JOptionPane.showMessageDialog(this,"Wrong input for marks");
        }
        else{
        int t = m1+m2+m3+m4+m5;
        float p = t/5;
        char g = 'A';
        if(p>=80){
            g ='A';
        }
        else if(p>=70 && p<80){
            g ='B';
        }
        else if(p>=60 && p<70){
            g ='C';
        }
        else if(p>=50 && p<60){
           g ='D';
        }
        else if(p>=40 && p<50){
            g ='E';
        }
        else if(p<40){
            g ='F';
        }
        String gs =String.valueOf(g); 
        pst.setLong(1,a);
        pst.setString(2,yos);
        pst.setString(3,ema.getText());
        pst.setInt(4,t);
        pst.setFloat(5, p);
        pst.setString(6, gs);
        pst.setString(7,name.getText());
        
        int r = pst.executeUpdate();
        pst.close();
        con.close();
        
        }
        }  catch(Exception e){ System.out.println("ERROR"+ e); } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ise1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise1ActionPerformed

    private void ese1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese1ActionPerformed

    private void ise2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise2ActionPerformed

    private void ese2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese2ActionPerformed

    private void ise3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise3ActionPerformed

    private void ese3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese3ActionPerformed

    private void ise4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise4ActionPerformed

    private void ese4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese4ActionPerformed

    private void ise5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ise5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ise5ActionPerformed

    private void ese5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ese5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ese5ActionPerformed

    private void ia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ia5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ia5ActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FY;
    private javax.swing.JRadioButton LY;
    private javax.swing.JRadioButton SY;
    private javax.swing.JRadioButton TY;
    private javax.swing.JTextField ema;
    private javax.swing.JLabel emao;
    private javax.swing.JTextField ese1;
    private javax.swing.JTextField ese2;
    private javax.swing.JTextField ese3;
    private javax.swing.JTextField ese4;
    private javax.swing.JTextField ese5;
    private javax.swing.JTextField ia1;
    private javax.swing.JTextField ia2;
    private javax.swing.JTextField ia3;
    private javax.swing.JTextField ia4;
    private javax.swing.JTextField ia5;
    private javax.swing.JTextField ise1;
    private javax.swing.JTextField ise2;
    private javax.swing.JTextField ise3;
    private javax.swing.JTextField ise4;
    private javax.swing.JTextField ise5;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameo;
    private javax.swing.JTextField roll;
    private javax.swing.JLabel rollnoo;
    private javax.swing.JLabel yoso;
    // End of variables declaration//GEN-END:variables
}
